# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - se4453final

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://gururacr01.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6bda9a74b9e9489e8802b849da8cc8d1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f2a30aa1984a4cf495c0d2f04a1b048c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: gururacr01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6bda9a74b9e9489e8802b849da8cc8d1 }}/se4453midterm:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'se4453final'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_de7eba4cc07e49fea0395e5488b76b89 }}
        images: 'gururacr01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6bda9a74b9e9489e8802b849da8cc8d1 }}/se4453midterm:${{ github.sha }}'