name: Build and deploy container app to Azure Web App - se4453final

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY_NAME: gururacr01.azurecr.io
  IMAGE_NAME: se4453midterm
  RESOURCE_GROUP: se4453_rg
  APP_SERVICE_NAME: se4453final

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ secrets.AzureAppService_ContainerUsername }}
          password: ${{ secrets.AzureAppService_ContainerPassword }}

      - name: Build and push image to ACR
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          images: ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest
