name: Build and deploy container app to Azure Web App - se4453final

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: azure/docker-login@v1
      with:
        login-server: se4453acr1.azurecr.io

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: se4453acr1.azurecr.io/se4453midterm:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: se4453midterm
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_de7eba4cc07e49fea0395e5488b76b89 }}
        images: se4453acr1.azurecr.io/se4453midterm:${{ github.sha }}
